title: "YTL課程講義"
<!-- description: MATLAB 與 AI 的課程講義-->
theme: jekyll-theme-Architect
baseurl: "/YTCourse"
<!-- url: "https://ytleetwgh.github.io"-->

<!-- remote_theme: pmarsceill/just-the-docs-->
collections:
  matlab:
    output: true
    permalink: /matlab/:name
  ai:
    output: true
    permalink: /ai/:name
