title: YTLee課程講義
description: MATLAB 與 AI 的課程講義
theme: jekyll-theme-Slate
baseurl: "/YTCourse"

collections:
  matlab:
    output: true
    permalink: /matlab/:name
  ai:
    output: true
    permalink: /ai/:name
