title: YT課程講義
theme: jekyll-theme-architect

collections:
  java:
    output: true
    permalink: /java/:name
  matlab:
    output: true
    permalink: /matlab/:name
  ai:
    output: true
    permalink: /ai/:namename
